version: "3.8"
services:
  postgres-db:
    image: postgres:17.0-alpine3.20
    hostname: postgres-db
    restart: always
    env_file:
      - .env
    volumes:
      - "./db:/var/lib/postgresql/data"
      - "./src/database/postgres/migrations:/docker-entrypoint-initdb.d/"
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    networks:
      - app-network
  app:
    build: .
    restart: always
    volumes:
      - ./src:/usr/src/app/src
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
       postgres-db:
        condition: service_healthy
    networks:
      - app-network
networks:
  app-network:
    driver: bridge